s = 'AATGACTTTAGAGCAGATGGACCATGATTGTTCGATCTTCTTGGAGATCTCGCACTGACGTGTGTCGCGTCGAGCGATAGTACCCGAATACAGACGGGGCCTGACATGGCCTGGACCCCGGAGGCGCCCAGTGGTTTGTTTGGCAACAGAGCAACGAGTCTCTTAGTTGGGGGTAGCCCACCCAGTTCCCACTTATTCTCATTTGAACCCTCCCCTACCCATGGAAAATCTGGTGCGGCAGTCGTGGCTTATCCGGTGTTGTGAAGGTCCGGCACATCTCCCGGGCCATGGCATAAAGTTCGTAGCCACACATTTTATGGCCGTCACAGCAGTTTTCTGGGTGCGACGGAGCCGTACAAATCGTCACCACCTAGGCGCCGCACTTGAGGTGGACGTGCCATAACATTTAACGACCACCGGATTCTGTTCCTCCGGCGTTTTCGCTATATATCGCAGTTTCCCCTAGGTGCAAACCACGAAGTCATCAGAAACGCGGTAATTCAATAGTCTTTGTCCAATATTTGCAATCCATTTACCGGAAATAGTAGTTACAGCGAAGGACGTAGATCAATACGTTGAATCTTCTCGTTCTCGCAGCTCCTTTTACATATCGAAGATTAAGTCTTAGATACCAAGTTTGCCTACCGACGTTTCCCACTAGCACTAGGGTCTTCTACACGAACCATCAATTCGAGCGATGCCCTCAGCATCCGTTCAGCAGTCTTTTCCCCATACGCGCTGTTCTTCCGCTTGGACACTGAAGACACTGTTATAAAGCAATTGATTAAGGAAAGAGAGCAATCAACCGGCCCAATGTATACCTTGCTCGAGGTCAGTCGTCCACTGATCTCAACCTCCTGAGCGATGTTTAATGCTCG'

def complement(s):
    sc = s[::-1]
    sc = sc.replace('G', '1')
    sc = sc.replace('C', 'G')
    sc = sc.replace('1', 'C')

    sc = sc.replace('A', '1')
    sc = sc.replace('T', 'A')
    sc = sc.replace('1', 'T')
    return sc

print complement(s)
